// Barrel file — re-exports from domain-specific modules for backward compatibility
export { ApiError } from './request'
export type {
  AdminAppointmentPayload,
  SeriesConflictResolution,
  SeriesDateConflict,
  SeriesPreviewResult,
  StatsResponse,
} from './admin'
export {
  verifyAdminToken,
  fetchDaySchedule,
  fetchAppointments,
  cancelAppointment,
  markAppointmentNoShow,
  deleteAppointment,
  fetchAdminAppointmentSeries,
  fetchStaffServicesForAdmin,
  fetchAdminSlots,
  createAdminAppointment,
  previewSeriesConflicts,
  updateAdminAppointment,
  fetchAdminMultiSlots,
  fetchAdminBlockSeries,
  createAdminBlock,
  updateAdminBlock,
  deleteAdminBlock,
  fetchCustomers,
  fetchCustomerDetail,
  sendCustomerReviewRequest,
  updateCustomer,
  createCustomer,
  deleteCustomer,
  fetchFullSchedule,
  updateSalonSchedule,
  fetchStaffSpecialSchedule,
  updateStaffSpecialSchedule,
  deleteStaffSpecialDate,
  updateStaffSchedule,
  fetchStats,
} from './admin'
export type { AdminService, AdminServiceCategory } from './admin-catalog'
export {
  fetchAdminServices,
  createAdminService,
  updateAdminService,
  deleteAdminService,
  hardDeleteAdminService,
  fetchAdminServiceCategories,
  createAdminServiceCategory,
  updateAdminServiceCategory,
  deleteAdminServiceCategory,
  hardDeleteAdminServiceCategory,
} from './admin-catalog'
export {
  fetchServices,
  fetchServiceCategories,
  fetchStaffForService,
  fetchSlots,
  fetchServiceDaySlots,
  fetchStaffAtSlot,
  fetchBookingChainContinuation,
  createAppointment,
} from './booking'
